server:
  port: 8001

spring:
  application:
    name: banking-client-dev
  
  # Development Database Configuration  
  datasource:
    url: jdbc:postgresql://gondola.proxy.rlwy.net:40809/railway
    username: postgres
    password: gVGvsyyMauTSYTpFwemcKILhuLuvUacf
    driver-class-name: org.postgresql.Driver
    
  # JPA Configuration for Development
  jpa:
    hibernate:
      ddl-auto: create-drop  # Recreate schema on startup
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

# Enhanced Logging for Development
logging:
  level:
    com.banking.client: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.transaction: DEBUG