server:
  port: 8002

spring:
  application:
    name: banking-account
  datasource:
    url: jdbc:postgresql://gondola.proxy.rlwy.net:40809/railway
    username: postgres
    password: gVGvsyyMauTSYTpFwemcKILhuLuvUacf
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized